CREATE USER 'ship'@'localhost' IDENTIFIED BY 'ship';
CREATE DATABASE shipdb DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
GRANT ALL PRIVILEGES ON shipdb.* TO 'ship'@'%' IDENTIFIED BY 'ship' WITH GRANT OPTION;
FLUSH PRIVILEGES;